# Generated by Django 2.1.15 on 2020-06-26 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_auto_20200626_1416'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('discription', models.TextField()),
                ('img', models.ImageField(upload_to='Banners/')),
            ],
        ),
    ]
