# Generated by Django 2.1.15 on 2020-06-28 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='percent',
            field=models.IntegerField(default=0),
        ),
    ]
