# Generated by Django 2.1.15 on 2020-06-29 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_product_percent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='percent',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
